Hamburgers changes made logo added
MicrosoftStudentChapter/makeathon6-website pull request #71
Opened 2024-02-09 09:00 UTC by MW-5705

2024-02-10 18:57 UTC, Siddharth-Agg-arwal requested changes
fix the mlsc logo position on the sponsors page (place it on the left)

2024-02-16 17:09 UTC, MankiratSingh1315 commented
Disable scroll when hamburger is opened

2024-02-17 10:48 UTC, MankiratSingh1315 submitted a review, later dismissed

2024-02-17 10:48 UTC, MankiratSingh1315 commented on app/page.module.css
> +
```suggestion
}
```

2024-02-17 11:25 UTC, Siddharth-Agg-arwal approved these changes

2024-02-17 11:25 UTC, Siddharth-Agg-arwal commented
changes reviewed

2024-02-17 11:26 UTC, merged